/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsNewRouteImport } from './routes/bots/new'
import { Route as BotsBotIdRouteImport } from './routes/bots/$botId'
import { Route as BotsBotIdMetricsRouteImport } from './routes/bots/$botId.metrics'
import { Route as BotsBotIdLogsRouteImport } from './routes/bots/$botId.logs'
import { Route as BotsBotIdEnvRouteImport } from './routes/bots/$botId.env'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdMetricsRoute = BotsBotIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => BotsBotIdRoute,
} as any)
const BotsBotIdLogsRoute = BotsBotIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => BotsBotIdRoute,
} as any)
const BotsBotIdEnvRoute = BotsBotIdEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => BotsBotIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/bots/$botId': typeof BotsBotIdRouteWithChildren
  '/bots/new': typeof BotsNewRoute
  '/bots/$botId/env': typeof BotsBotIdEnvRoute
  '/bots/$botId/logs': typeof BotsBotIdLogsRoute
  '/bots/$botId/metrics': typeof BotsBotIdMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/bots/$botId': typeof BotsBotIdRouteWithChildren
  '/bots/new': typeof BotsNewRoute
  '/bots/$botId/env': typeof BotsBotIdEnvRoute
  '/bots/$botId/logs': typeof BotsBotIdLogsRoute
  '/bots/$botId/metrics': typeof BotsBotIdMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/bots/$botId': typeof BotsBotIdRouteWithChildren
  '/bots/new': typeof BotsNewRoute
  '/bots/$botId/env': typeof BotsBotIdEnvRoute
  '/bots/$botId/logs': typeof BotsBotIdLogsRoute
  '/bots/$botId/metrics': typeof BotsBotIdMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/bots/$botId'
    | '/bots/new'
    | '/bots/$botId/env'
    | '/bots/$botId/logs'
    | '/bots/$botId/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/bots/$botId'
    | '/bots/new'
    | '/bots/$botId/env'
    | '/bots/$botId/logs'
    | '/bots/$botId/metrics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/bots/$botId'
    | '/bots/new'
    | '/bots/$botId/env'
    | '/bots/$botId/logs'
    | '/bots/$botId/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRoute
  BotsBotIdRoute: typeof BotsBotIdRouteWithChildren
  BotsNewRoute: typeof BotsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId/metrics': {
      id: '/bots/$botId/metrics'
      path: '/metrics'
      fullPath: '/bots/$botId/metrics'
      preLoaderRoute: typeof BotsBotIdMetricsRouteImport
      parentRoute: typeof BotsBotIdRoute
    }
    '/bots/$botId/logs': {
      id: '/bots/$botId/logs'
      path: '/logs'
      fullPath: '/bots/$botId/logs'
      preLoaderRoute: typeof BotsBotIdLogsRouteImport
      parentRoute: typeof BotsBotIdRoute
    }
    '/bots/$botId/env': {
      id: '/bots/$botId/env'
      path: '/env'
      fullPath: '/bots/$botId/env'
      preLoaderRoute: typeof BotsBotIdEnvRouteImport
      parentRoute: typeof BotsBotIdRoute
    }
  }
}

interface BotsBotIdRouteChildren {
  BotsBotIdEnvRoute: typeof BotsBotIdEnvRoute
  BotsBotIdLogsRoute: typeof BotsBotIdLogsRoute
  BotsBotIdMetricsRoute: typeof BotsBotIdMetricsRoute
}

const BotsBotIdRouteChildren: BotsBotIdRouteChildren = {
  BotsBotIdEnvRoute: BotsBotIdEnvRoute,
  BotsBotIdLogsRoute: BotsBotIdLogsRoute,
  BotsBotIdMetricsRoute: BotsBotIdMetricsRoute,
}

const BotsBotIdRouteWithChildren = BotsBotIdRoute._addFileChildren(
  BotsBotIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRoute,
  BotsBotIdRoute: BotsBotIdRouteWithChildren,
  BotsNewRoute: BotsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
